import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Rakesh',
      email: 'rakesh@gowda.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Sushmitha',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'POCO M4 Pro 5G',
      slug: 'POCO-Pro-5G',
      category: 'Mobiles',
      image: '/images/p1.jpg',
      price: 14999,
      countInStack: 10,
      brand: 'POCO',
      rating: 4.5,
      numReviews: 10,
      description: 'Samsung Galaxy M33 5G  50 MP + 5 MP + 2 MP + 2 MP cameras',
    },
    {
      // _id: '2',
      name: 'OnePlus Nord CE 2 Lite 5G',
      slug: 'OnePlus-Nord-CE',
      category: 'Mobiles',
      image: '/images/p2.jpg',
      price: 18999,
      countInStack: 0,
      brand: 'OnePlus',
      rating: 4.8,
      numReviews: 10,
      description:
        'OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM, 128GB Storage)',
    },
    {
      // _id: '3',
      name: 'Oppo A54',
      slug: 'Oppo-A54',
      category: 'Mobiles',
      image: '/images/p3.jpg',
      price: 10990,
      countInStack: 15,
      brand: 'Oppo',
      rating: 4.0,
      numReviews: 10,
      description: 'Oppo A54 (Crystal Black, 4GB RAM, 64GB Storage)',
    },
    {
      // _id: '4',
      name: 'Redmi 10 Prime',
      slug: 'Redmi-Prime',
      category: 'Mobiles',
      image: '/images/p4.jpg',
      price: 12498,
      countInStack: 20,
      brand: 'Redmi',
      rating: 4.7,
      numReviews: 10,
      description: 'Redmi 10 Prime 128 GB, 6 GB RAM, Phantom Black',
    },
    {
      // _id: '5',
      name: 'Apple iPhone 14 Pro Max',
      slug: 'Apple iPhone',
      category: 'Mobiles',
      image: '/images/p5.jpg',
      price: 149900,
      countInStack: 20,
      brand: 'iPhone',
      rating: 4.8,
      numReviews: 10,
      description: 'Apple iPhone 14 Pro Max 256 GB (Deep Purple, 6 GB RAM)',
    },
    {
      // _id: '6',
      name: 'MOTOROLA g52',
      slug: 'MOTOROLA g52',
      category: 'Mobiles',
      image: '/images/p6.jpg',
      price: 11999,
      countInStack: 20,
      brand: 'MOTOROLA',
      rating: 4.7,
      numReviews: 10,
      description: 'MOTOROLA g52 (Charcoal Grey, 64 GB)  (4 GB RAM)',
    },
  ],
};
export default data;